# Usage:
#   docker-compose -f docker-compose-zalenium.yml up --build
#   Live test availble at http://localhost:4444/grid/admin/live you can view videos after test finishes at http://localhost:4444/dashboard/#
version: "3"
services:

  hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2

    ports:
      - "5566:5555"

  chrome2:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    ports:
      - "5577:5555"

  firefox:
    image: selenium/node-firefox:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    ports:
      - "5588:5555"
